// <auto-generated />
namespace SlotMe.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MarkMajors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MarkMajors));
        
        string IMigrationMetadata.Id
        {
            get { return "202011200140383_Mark Majors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
